apiVersion: events.ibm.com/v1beta1
kind: EventGateway
metadata:
  name: "gw1-default-gw"
spec:
  license:
    accept: false
    license: "L-CYBH-K48BZQ"
    metric: "VIRTUAL_PROCESSOR_CORE"
    use: "EventAutomationNonProduction"
  managerEndpoint: "https://eem.event-automation-e7d3d93b8b317d269525bf063b24f98d-0000.eu-de.containers.appdomain.cloud/gateway"
  maxNumKafkaBrokers: 20
  gatewayGroupName: "gw1"
  gatewayID: "default-gw"
  replicas: 1
  template:
    pod:
      spec:
        containers:
          - name: egw
            env:
              - name: BACKEND_CA_CERTIFICATES
                value: "-----BEGIN CERTIFICATE-----\nMIIDbDCCAlSgAwIBAgIQSASK478CIf8TDe2xO1KMrDANBgkqhkiG9w0BAQsFADBQ\nMSYwJAYDVQQKEx1JQk0gRXZlbnQgRW5kcG9pbnQgTWFuYWdlbWVudDEmMCQGA1UE\nAxMdSUJNIEV2ZW50IEVuZHBvaW50IE1hbmFnZW1lbnQwHhcNMjUwNjIzMDkyMTMx\nWhcNMjYwNjIzMDkyMTMxWjBQMSYwJAYDVQQKEx1JQk0gRXZlbnQgRW5kcG9pbnQg\nTWFuYWdlbWVudDEmMCQGA1UEAxMdSUJNIEV2ZW50IEVuZHBvaW50IE1hbmFnZW1l\nbnQwggEiMA0GCSqGSIb3DQEBAQUAA4IBDwAwggEKAoIBAQDTF+6h536F8OjGnD4Z\npXZOWK/hLGSWhAYV/vPEt/ZZWGpi3dvirWu+LT3eQF8AGhhJL6XNusX89QcNWRbY\nOLY876w+/ot8BxvTkpuFCL679GZQ59wMU1OJIucgw5IHANcOkPLyHMvsxuqqaxzv\noUF8vbfdYqh+mvny0SbjrFE9EQCdgdpCKm/0eKZWLPRyDNkfKoOU/qABjfszJU6M\nVROiLArbSP4FG0xTsIIDlv7YbsRUI+KDZlExDE2M40Uw0Qfqt78GuCKNeYb8tQdo\nnaoC1SKIOMGuuVY024UCHSzmF5QuNtJbfPBcXnIiU+tTlGdVVqzHDglPKU/8hJRW\naigrAgMBAAGjQjBAMA4GA1UdDwEB/wQEAwICpDAPBgNVHRMBAf8EBTADAQH/MB0G\nA1UdDgQWBBTxrvfZM5v28b6uUFxH5XFRiGatTTANBgkqhkiG9w0BAQsFAAOCAQEA\nI1IYSJ6B8HeN98/15LaQoaqYW/sbafcZR2Vbi9esZPXf1voKNyqXpbaIXwdUZYYc\nTyeKOeTSR2s6VptdqQooJsQlzUr3P9HlP8yOYaRIxGDcJsZCdmDeS/njqSTk0Bts\nktxkWkCiQjH+xRbJud/eDF7UKl6BKyQ6jaQmIB+e1r0yL5z/enF4E0UWpFwvVjVl\nqGTmaAl+jC8FC8lNhAUClIpC7Wcx4lXeMRdX6aAs3ynL9RF28Dd6Z/s5gRmYgEMp\ns4SaTrpz5hufcS5kZzDjX4mKb+J/oT2xGGVsUV6TqKPbo5NUdpTL69OIJ24IoJaP\nwz/HZmYW0SPYGpnixDf4sw==\n-----END CERTIFICATE-----\n"
              - name: API_KEY
                valueFrom:
                  secretKeyRef:
                    key: apiKey
                    name: "gw1-default-gw"
              - name: GATEWAY_TRUST_PEM
                valueFrom:
                  secretKeyRef:
                    key: tls.crt
                    name: "gw1-default-gw-certs"
  tls:
    caSecretName: "gw1-default-gw-certs"
---
apiVersion: v1
kind: Secret
metadata:
  name: "gw1-default-gw-certs"
  labels:
    app: "gw1-default-gw"
type: Opaque
stringData:
  # Provide CA certificate and key in PEM format
  tls.crt: <tls-certificate>
  tls.key: <tls-key>
---
apiVersion: v1
kind: Secret
metadata:
  name: "gw1-default-gw"
  labels:
    app: "gw1-default-gw"
type: Opaque
stringData:
  apiKey: "2a067c4e-f323-45dd-9f30-eab0eb0c0b77"