apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: gateway-server-certificate
spec:
  secretTemplate:
    labels:
      app: "gw1-default-gw"
  secretName: gw1-default-gw-certs
  duration: 2160h0m0s # 90d
  renewBefore: 360h0m0s # 15d
  subject:
    organizations:
      - ibm
  privateKey:
    algorithm: RSA
    encoding: PKCS1
    size: 2048
  usages:
    - key encipherment
    - digital signature
    - server auth
    - client auth
  dnsNames:
    - 'gateway.event-automation-e7d3d93b8b317d269525bf063b24f98d-0000.eu-de.containers.appdomain.cloud'
  issuerRef:
    name: letsencrypt-cluster-issuer
    kind: ClusterIssuer