apiVersion: events.ibm.com/v1beta1
kind: EventGateway
metadata:
  name: "gw1-default-gw"
spec:
  license:
    accept: true
    license: "L-CYBH-K48BZQ"
    metric: "VIRTUAL_PROCESSOR_CORE"
    use: "EventAutomationNonProduction"
  managerEndpoint: https://eem.event-automation-e7d3d93b8b317d269525bf063b24f98d-0000.eu-de.containers.appdomain.cloud/gateway
  maxNumKafkaBrokers: 3
  gatewayGroupName: "gw1"
  gatewayID: "default-gw"
  replicas: 1
  template:
    pod:
      spec:
        containers:
          - name: egw
            env:
              # For communication with the event manager. Either use the supplied value from the generated 
              # gateway CR, or point to secret.
              - name: BACKEND_CA_CERTIFICATES
                valueFrom:
                  secretKeyRef:
                    key: tls.crt
                    #name: "eventendpointmanagement-ibm-eem-manager"
                    name: eem-manager-cert-secret
              - name: API_KEY
                valueFrom:
                  secretKeyRef:
                    key: apiKey
                    name: "gw1-default-gw"
              - name: GATEWAY_TRUST_PEM
                valueFrom:
                  secretKeyRef:
                    key: tls.crt
                    name: "gw1-default-gw-certs"
                    #name: eem-gateway-cert-lec-secret
  
  # See https://ibm.github.io/event-automation/eem/reference/api-reference/#resource-endpoint
  endpoints:
    - name: gateway
      host: gateway.event-automation-e7d3d93b8b317d269525bf063b24f98d-0000.eu-de.containers.appdomain.cloud
      class: public-iks-k8s-nginx
  
  # Provide either a server certificate or a CA certificate to be used for creating certificates. 
  # This is TLS config for the communication between Kafka clients and the gateway
  # See https://ibm.github.io/event-automation/eem/reference/api-reference/#resource-tls
  tls:
    secretName: eem-gateway-cert-lec-secret
    #secretName: "gw1-default-gw-certs"
    serverCertificate: tls.crt
    key: tls.key
    #trustedCertificates:
    #  secretName: letsencrypt-chain
    #  certificate: ca.crt
---
apiVersion: v1
kind: Secret
metadata:
  name: "gw1-default-gw"
  labels:
    app: "gw1-default-gw"
type: Opaque
stringData:
  apiKey: 27ea0934-4856-46ab-8e1c-341cb790d91c