apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: eem-gateway-cert-request
spec:
  secretName: gw1-default-gw-certs-ss
  privateKey:
    algorithm: RSA
  duration: 2160h # 90d
  renewBefore: 360h # 15d
  isCA: false
  usages:
    - server auth
  subject:
    organizations:
      - cert-manager
  commonName: <common name>
  dnsNames:
    - gw1-default-gw-1.event-automation-e7d3d93b8b317d269525bf063b24f98d-0000.eu-de.containers.appdomain.cloud
    - gw1-default-gw-2.event-automation-e7d3d93b8b317d269525bf063b24f98d-0000.eu-de.containers.appdomain.cloud
    - gw1-default-gw-3.event-automation-e7d3d93b8b317d269525bf063b24f98d-0000.eu-de.containers.appdomain.cloud
  issuerRef:
    name: eem-ca-issuer
    kind: ClusterIssuer