apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: eem-manager-cert
  labels:
    app: eventendpointmanagement
spec:
  secretName: eem-manager-cert-secret
  secretTemplate:
    labels:
      app: eventendpointmanagement
  privateKey:
    algorithm: RSA
  duration: 2160h # 90d
  renewBefore: 360h # 15d
  isCA: false
  usages:
    - client auth
    - digital signature
    - server auth
  subject:
    organizations:
      - eventendpointmanager
  dnsNames:
    - qs-eem-gateway.event-automation-e7d3d93b8b317d269525bf063b24f98d-0000.eu-de.containers.appdomain.cloud
    - eem-ui.event-automation-e7d3d93b8b317d269525bf063b24f98d-0000.eu-de.containers.appdomain.cloud
    - qs-eem-admin.event-automation-e7d3d93b8b317d269525bf063b24f98d-0000.eu-de.containers.appdomain.cloud
    - eem.event-automation-e7d3d93b8b317d269525bf063b24f98d-0000.eu-de.containers.appdomain.cloud
  issuerRef:
    name: letsencrypt-issuer
    kind: Issuer