apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: manager-ui-certificate
spec:
  secretName: manager-ui-certificate-secret
  duration: 2160h0m0s # 90d
  renewBefore: 360h0m0s # 15d
  subject:
    organizations:
      - ibm
  privateKey:
    algorithm: RSA
    encoding: PKCS1
    size: 2048
  usages:
    - key encipherment
    - digital signature
    - server auth
    - client auth
  dnsNames:
    - qs-eem-ui.event-automation-e7d3d93b8b317d269525bf063b24f98d-0000.eu-de.containers.appdomain.cloud
  issuerRef:
    name: letsencrypt-cluster-issuer
    kind: ClusterIssuer