apiVersion: events.ibm.com/v1beta1
kind: EventEndpointManagement
metadata:
  name: eventendpointmanagement
  labels:
    backup.events.ibm.com/component: eventendpointmanagement
spec:
  license:
    accept: true
    license: 'L-CYBH-K48BZQ'
    metric: VIRTUAL_PROCESSOR_CORE
    use: EventAutomationNonProduction
  manager:
    # See https://ibm.github.io/event-automation/eem/reference/api-reference/#resource-endpoint
    endpoints:
      - name: ui
        host: ui.event-automation-e7d3d93b8b317d269525bf063b24f98d-0000.eu-de.containers.appdomain.cloud
        class: public-iks-k8s-nginx
      - name: gateway
        host: gateway.event-automation-e7d3d93b8b317d269525bf063b24f98d-0000.eu-de.containers.appdomain.cloud
        class: public-iks-k8s-nginx
      - name: admin
        host: admin.event-automation-e7d3d93b8b317d269525bf063b24f98d-0000.eu-de.containers.appdomain.cloud
        class: public-iks-k8s-nginx
      - name: server
        host: eem.eventendpointmanagement.event-automation-e7d3d93b8b317d269525bf063b24f98d-0000.eu-de.containers.appdomain.cloud
        class: public-iks-k8s-nginx
      - name: apic 
        host: apic.event-automation-e7d3d93b8b317d269525bf063b24f98d-0000.eu-de.containers.appdomain.cloud
        class: public-iks-k8s-nginx
    authConfig:
      authType: OIDC
      oidcConfig:
         clientIDKey: client-id
         clientSecretKey: client-secret
         discovery: true
         secretName: oidc-secret
         site: https://eu-de.appid.cloud.ibm.com/oauth/v4/ba53a653-a64c-4a41-b6ce-4718cbde1497/
    storage:
      type: persistent-claim
      #storageClassName: ibmc-vpc-block-10iops-tier
      deleteClaim: false
      existingClaimName: eem-storage
    # See: https://ibm.github.io/event-automation/eem/reference/api-reference/#resource-tls
    tls:
      secretName: eem-manager-cert-secret
      serverCertificate: tls.crt
      caCertificate: tls.crt
      key: tls.key
      trustedCertificates:
        - certificate: ca.crt
          secretName: apim-cpd
    # See https://ibm.github.io/event-automation/eem/reference/api-reference/#resource-apic
    apic:
      jwks:
        #endpoint: https://apic-clust-5e7e2547-platform-api-cp4i.apps.itz-yk8hp3.hub01-lb.techzone.ibm.com/api/cloud/oauth2/certs
        endpoint: https://apic-clust-48d1a43f-platform-api-cp4i.apps.itz-iw49ak.infra01-lb.fra02.techzone.ibm.com/api/cloud/oauth2/certs
    #traceSpec: "com.ibm.ei.apic.ingress:trace"
    template:
      pod:
        spec:
          containers:
            - name: manager
              env:
              - name: TZ
                value: "Europe/Stockholm"
              - name: IBM_JAVA_OPTS
                value: "-Djavax.net.debug=ssl,handshake,certpath"
              - name: IBM_JAVA_OPTIONS
                value: "-Djavax.net.debug=ssl,handshake,certpath"
              resources:
                requests:
                  cpu: '0.25'
                  memory: 256Mi
                limits:
                  cpu: '0.5'
                  memory: 512Mi
