apiVersion: events.ibm.com/v1beta1
kind: EventEndpointManagement
metadata:
  name: eventendpointmanagement
  labels:
    backup.events.ibm.com/component: eventendpointmanagement
spec:
  license:
    accept: true
    license: 'L-CYBH-K48BZQ'
    metric: VIRTUAL_PROCESSOR_CORE
    use: EventAutomationNonProduction
  manager:
    endpoints:
      - name: ui
        host: qs-eem-ui.event-automation-e7d3d93b8b317d269525bf063b24f98d-0000.eu-de.containers.appdomain.cloud
        class: public-iks-k8s-nginx
      - name: gateway
        host: qs-eem-gateway.event-automation-e7d3d93b8b317d269525bf063b24f98d-0000.eu-de.containers.appdomain.cloud
        class: public-iks-k8s-nginx
      - name: admin
        host: qs-eem-admin.event-automation-e7d3d93b8b317d269525bf063b24f98d-0000.eu-de.containers.appdomain.cloud
        class: public-iks-k8s-nginx
      - name: server
        host: eem.qs-eem-server.event-automation-e7d3d93b8b317d269525bf063b24f98d-0000.eu-de.containers.appdomain.cloud
        class: public-iks-k8s-nginx
    authConfig:
      authType: LOCAL
    storage:
      type: ephemeral
    tls:
      trustedCertificates:
        secretName: letsencrypt-chain
        certificate: x1-root.crt
    template:
      pod:
        spec:
          containers:
            - name: manager
              resources:
                requests:
                  cpu: '0.25'
                  memory: 256Mi
                limits:
                  cpu: '0.5'
                  memory: 512Mi