apiVersion: events.ibm.com/v1beta1
kind: EventEndpointManagement
metadata:
  name: eventendpointmanagement
  labels:
    backup.events.ibm.com/component: eventendpointmanagement
spec:
  license:
    accept: true
    license: 'L-CYBH-K48BZQ'
    metric: VIRTUAL_PROCESSOR_CORE
    use: EventAutomationNonProduction
  manager:
    # See https://ibm.github.io/event-automation/eem/reference/api-reference/#resource-endpoint
    endpoints:
      - name: ui
        host: eem-ui.event-automation-e7d3d93b8b317d269525bf063b24f98d-0000.eu-de.containers.appdomain.cloud
        class: public-iks-k8s-nginx
      - name: gateway
        host: qs-eem-gateway.event-automation-e7d3d93b8b317d269525bf063b24f98d-0000.eu-de.containers.appdomain.cloud
        class: public-iks-k8s-nginx
      - name: admin
        host: qs-eem-admin.event-automation-e7d3d93b8b317d269525bf063b24f98d-0000.eu-de.containers.appdomain.cloud
        class: public-iks-k8s-nginx
      - name: server
        host: eem.event-automation-e7d3d93b8b317d269525bf063b24f98d-0000.eu-de.containers.appdomain.cloud
        class: public-iks-k8s-nginx
      - name: apic 
        host: apic.event-automation-e7d3d93b8b317d269525bf063b24f98d-0000.eu-de.containers.appdomain.cloud
        class: public-iks-k8s-nginx
    authConfig:
      authType: LOCAL
    storage:
      type: persistent-claim
      storageClassName: ibmc-vpc-block-10iops-tier
    # See: https://ibm.github.io/event-automation/eem/reference/api-reference/#resource-tls
    # tls:
    #   trustedCertificates:
    #     - certificate: ca.crt
    #       secretName: <name of secret containing the ca.crt of your API Connect instance, required if using a different CA to EEM>
    # See https://ibm.github.io/event-automation/eem/reference/api-reference/#resource-apic
    # apic:
    #   jwks:
    #     endpoint: <end point>
    template:
      pod:
        spec:
          containers:
            - name: manager
              resources:
                requests:
                  cpu: '0.25'
                  memory: 256Mi
                limits:
                  cpu: '0.5'
                  memory: 512Mi