apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - eventendpointmanagement.yaml
  #- tls/letsencrypt/letsencrypt-issuer.yaml
  #- tls/letsencrypt/manager-certificate.yaml

secretGenerator:
  # - name: eventendpointmanagement-ibm-eem-user-credentials
  #   files:
  #     - user-credentials.json

  - name: eventendpointmanagement-ibm-eem-user-roles
    files:
      - user-mapping.json

generatorOptions:
  disableNameSuffixHash: true

transformers:
  # - |-
  #   apiVersion: builtin
  #   kind: PatchTransformer
  #   metadata:
  #     name: add-annotation-user-credentials-secret
  #   patch: |-
  #     apiVersion: v1
  #     kind: Secret
  #     metadata:
  #       name: eventendpointmanagement-ibm-eem-user-credentials
  #       annotations:
  #         argocd.argoproj.io/sync-options: ServerSideApply=true
  #     type: Opaque
  - |-
    apiVersion: builtin
    kind: PatchTransformer
    metadata:
      name: add-annotation-roles-secret
    patch: |-
      apiVersion: v1
      kind: Secret
      metadata:
        name: eventendpointmanagement-ibm-eem-user-roles
        annotations:
          argocd.argoproj.io/sync-options: ServerSideApply=true
      type: Opaque
