kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: eem-storage
  namespace: ibm-event-automation
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: ibmc-vpc-block-10iops-tier
  volumeMode: Filesystem