apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml

# secretGenerator:
# - name: letsencrypt-chain
#   files:
#     - x1-root.crt=letsencrypt/x1-root.pem
#     - r10.crt=letsencrypt/r10.pem
#     - r11.crt=letsencrypt/r11.pem
#   type: "Opaque"

# generatorOptions:
#   disableNameSuffixHash: true