apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: eventmanager
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: '200'
spec:
  destination:
    namespace: argocd
    server: https://kubernetes.default.svc
  project: default
  source:
    path: ./components/eventmanager
  syncPolicy:
    automated:
      prune: true
      selfHeal: true