apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: gateway
  namespace: argocd
  labels:
    group: applications
  annotations:
    argocd.argoproj.io/sync-wave: '200'
spec:
  destination:
    namespace: ibm-event-automation
    server: https://kubernetes.default.svc
  project: default
  source:
    path: ./components/gateway
  syncPolicy:
    automated:
      prune: true
      selfHeal: true