apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:

  - eem-crds.yaml
  - eem-operator.yaml
  #- common.yaml
  #- instances-applicationset.yaml

patches:
- target:
    group: argoproj.io
    kind: Application
    labelSelector: group=applications
  patch: |-
    - op: add
      path: /spec/source/repoURL
      value: https://github.com/kjellmlarsson/eem-iks.git
    - op: add
      path: /spec/source/targetRevision
      value: HEAD
- target:
    group: argoproj.io
    kind: ApplicationSet
  patch: |-
    - op: add
      path: /spec/template/spec/source/repoURL
      value: https://github.com/kjellmlarsson/eem-iks.git
    - op: add
      path: /spec/template/spec/source/targetRevision
      value: HEAD
