apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: selfsigned-issuer
spec:
  selfSigned: {}
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: eem-selfsigned-ca-cert
spec:
  isCA: true 
  commonName: eem-selfsigned-ca
  secretName: ca-root-secret
  privateKey:
    algorithm: RSA
  issuerRef:
    name: selfsigned-issuer
    kind: Issuer
    group: cert-manager.io
---
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: eem-ca-issuer
spec:
  ca:
    secretName: ca-root-secret