apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: eem-gateway-cert-lec
  labels:
    app: eventendpointmanagement
spec:
  secretName: eem-gateway-cert-lec-secret
  secretTemplate:
    labels:
      app: eventgateway
  privateKey:
    algorithm: RSA
  duration: 2160h # 90d
  renewBefore: 360h # 15d
  isCA: false
  usages:
    - client auth
    - digital signature
    - server auth
  subject:
    organizations:
      - eventgateway

  dnsNames:
    - gw.event-automation-e7d3d93b8b317d269525bf063b24f98d-0000.eu-de.containers.appdomain.cloud
    - gw-1.event-automation-e7d3d93b8b317d269525bf063b24f98d-0000.eu-de.containers.appdomain.cloud
    - gw-2.event-automation-e7d3d93b8b317d269525bf063b24f98d-0000.eu-de.containers.appdomain.cloud
  issuerRef:
    name: letsencrypt-issuer
    kind: Issuer